### ISSUE TITLE
mediaPlatform.fileManager.uploadFile fails with Error: {"message":"no file posted","code":400,"payload":null}

### ISSUE THREAD

**Issue by a1gucis** [wix/media-platform-js-sdk#6]
Hi,

mediaPlatform.fileManager.uploadFile fails with Error: {"message":"no file posted","code":400,"payload":null} when trying to upload Buffer. 
Example code:

`
const fs = require('fs');
const MediaPlatform = require('media-platform-js-sdk').MediaPlatform;
const UploadFileRequest = require('media-platform-js-sdk').file.UploadFileRequest;

const video = fs.readFileSync(path.join('path', 'to',  'movie.mp4'));
const mediaPlatform = new MediaPlatform({
    domain: DOMAIN,
    appId: APP_ID,
    sharedSecret: SHARED_SECRET
});
const request = new UploadFileRequest().setMimeType('video/mp4');
mediaPlatform.fileManager.uploadFile('/videos/video.mp4', video, request, function(err, response) {
    if (err) {
      console.log(err);
    } else {
      console.log(response);
    }})
`

**Comment by andriichyzh** [comment]
Thanks for the detailed description. 
I reproduced the problem. 
I'll let you know when it will be fixed.

**Comment by andriichyzh** [comment]
I created pull request with fix.
@Elad-Laufer, please review https://github.com/wix/media-platform-js-sdk/pull/7

**Comment by andriichyzh** [comment]
@a1gucis bug fixed in version `5.0.52-beta` or higher.
Please, update it and try.
In case of any questions - we will be happy to help!

**Comment by andriichyzh** [comment]
Got confirmation about correct work after fix.
I close as resolved.
